# Define the directory containing your SQL files
$storedProceduresPath = ".\SQL\Stored Procedures"
$tablesPath = ".\SQL\Tables"

# Define the output file
$outputFile = "sqlSeed.sql"

# Get all .sql files in the directory and its subdirectories
$tableFiles = Get-ChildItem -Path $tablesPath -Include *.sql -Recurse -File
$storedProceduresFiles = Get-ChildItem -Path $storedProceduresPath -Include *.sql -Recurse -File

# Create an empty array to hold the content of the SQL files
$merged = @()

# Add a warning that the file can be regenerated by running the script
$merged += "/*`nThis file was generated by generateSqlSeed.ps1`n*/`n"

#Add a note to remember to use the correct database
$merged += "/*`nRemember to switch to the correct database`n*/`n"

# Add R8titSchema if not exists
$merged += "IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'R8titSchema')`nBEGIN`nEXEC('CREATE SCHEMA R8titSchema')`nEND`nGO`n"

# Loop through each table file
foreach ($tableFile in $tableFiles) {
    # Read the content of the SQL file and add it to the array
    $content = Get-Content -Path $tableFile.FullName
    $merged += $content
    # Add 'GO' statement
    $merged += "`nGO`n"
}

# Loop through each stored procedure file
foreach ($storedProceduresFile in $storedProceduresFiles) {
    # Read the content of the SQL file and add it to the array
    $content = Get-Content -Path $storedProceduresFile.FullName
    $merged += $content
    # Add 'GO' statement
    $merged += "`nGO`n"
}


# Write the content of the SQL files to a single file
$merged | Out-File -FilePath $outputFile